/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * An enumeration.
 */
export enum AppointmentStatus {
    Confirmed = "confirmed",
    Pending = "pending",
    InProgress = "in_progress",
    Completed = "completed",
    Cancelled = "cancelled",
}
