/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { DaySlots } from "./dayslots";
import { Expose, Type } from "class-transformer";

export class AppointmentAvailabilitySlots extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: DaySlots })
    @Expose({ name: "slots" })
    @Type(() => DaySlots)
    slots: DaySlots[];

    @SpeakeasyMetadata()
    @Expose({ name: "timezone" })
    timezone?: string;
}
