/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Pydantic BaseModel that supports `hidden` field property.
 *
 * @remarks
 *
 * A field with `hidden=True` will not be included in the schema (OpenAPI spec).
 */
export class AppointmentBookingRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "booking_key" })
    bookingKey: string;
}
