/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PhlebotomyAreaInfo } from "./phlebotomyareainfo";
import { Expose, Type } from "class-transformer";

export class AreaInfo extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "phlebotomy" })
    @Type(() => PhlebotomyAreaInfo)
    phlebotomy: PhlebotomyAreaInfo;

    @SpeakeasyMetadata()
    @Expose({ name: "zip_code" })
    zipCode: string;
}
