/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * An enumeration.
 */
export enum AuthType {
    Password = "password",
    Oauth = "oauth",
    Email = "email",
}
