/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class BrandInformation extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "brand_color" })
    brandColor: string;

    @SpeakeasyMetadata()
    @Expose({ name: "company_address" })
    companyAddress: string;

    @SpeakeasyMetadata()
    @Expose({ name: "company_name" })
    companyName: string;

    @SpeakeasyMetadata()
    @Expose({ name: "company_website" })
    companyWebsite: string;

    @SpeakeasyMetadata()
    @Expose({ name: "support_email" })
    supportEmail: string;
}
