/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { LabTestCollectionMethod } from "./labtestcollectionmethod";
import { LabTestSampleType } from "./labtestsampletype";
import { Expose } from "class-transformer";

export class ClientFacingLab extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "city" })
    city: string;

    @SpeakeasyMetadata()
    @Expose({ name: "collection_methods" })
    collectionMethods: LabTestCollectionMethod[];

    @SpeakeasyMetadata()
    @Expose({ name: "first_line_address" })
    firstLineAddress: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "sample_types" })
    sampleTypes: LabTestSampleType[];

    @SpeakeasyMetadata()
    @Expose({ name: "slug" })
    slug: string;

    @SpeakeasyMetadata()
    @Expose({ name: "zipcode" })
    zipcode: string;
}
