/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * A vendor, a service, or a platform which Vital can connect with.
 */
export class ClientFacingProvider extends SpeakeasyBase {
    /**
     * URL for source logo
     */
    @SpeakeasyMetadata()
    @Expose({ name: "logo" })
    logo: string;

    /**
     * Name of source of information
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * Slug for designated source
     */
    @SpeakeasyMetadata()
    @Expose({ name: "slug" })
    slug: string;
}
