/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

/**
 * Measured in counts
 */
export enum ClientFacingFloorsClimbedTimeseriesUnit {
    Count = "count",
}

export class ClientFacingFloorsClimbedTimeseries extends SpeakeasyBase {
    /**
     * Deprecated
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: any;

    /**
     * The timestamp of the measurement.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "timestamp" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    timestamp: Date;

    /**
     * Time zone UTC offset in seconds. Positive offset indicates east of UTC; negative offset indicates west of UTC; and null indicates the time zone information is unavailable at source.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "timezone_offset" })
    timezoneOffset?: number;

    /**
     * The reading type of the measurement. This is applicable only to Cholesterol, IGG and IGE.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: string;

    /**
     * Measured in counts
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unit" })
    unit: ClientFacingFloorsClimbedTimeseriesUnit;

    /**
     * Number of floors climbed at the time or interval::count
     */
    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value: number;
}
