/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class ClientFacingDiagnosisInformation extends SpeakeasyBase {
    /**
     * Diagnosis description insurance information required by Labcorp.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description: string;

    /**
     * Diagnosis code for insurance information required by Labcorp.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "diagnosis_code" })
    diagnosisCode: string;
}
