/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ClientFacingApiKey } from "./clientfacingapikey";
import { TeamConfig } from "./teamconfig";
import { Expose, Type } from "class-transformer";

export class ClientFacingTeam extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "airtable_api_key" })
    airtableApiKey?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "airtable_base_id" })
    airtableBaseId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "api_key" })
    apiKey?: string;

    @SpeakeasyMetadata({ elemType: ClientFacingApiKey })
    @Expose({ name: "api_keys" })
    @Type(() => ClientFacingApiKey)
    apiKeys?: ClientFacingApiKey[];

    @SpeakeasyMetadata()
    @Expose({ name: "client_id" })
    clientId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "client_secret" })
    clientSecret?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "configuration" })
    @Type(() => TeamConfig)
    configuration?: TeamConfig;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    @SpeakeasyMetadata()
    @Expose({ name: "lab_tests_patient_communication_enabled" })
    labTestsPatientCommunicationEnabled: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "lab_tests_patient_email_communication_enabled" })
    labTestsPatientEmailCommunicationEnabled: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "lab_tests_patient_sms_communication_enabled" })
    labTestsPatientSmsCommunicationEnabled: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "logo_url" })
    logoUrl?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "svix_app_id" })
    svixAppId?: string;

    /**
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "testkits_texts_enabled" })
    testkitsTextsEnabled: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "webhook_secret" })
    webhookSecret?: string;
}
