/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ConnectedSourceClientFacing } from "./connectedsourceclientfacing";
import { Expose, Transform, Type } from "class-transformer";

/**
 *
 * @remarks
 *     Fallback time zone of the user, in the form of a valid IANA tzdatabase identifier (e.g., `Europe/London` or `America/Los_Angeles`).
 *     Used when pulling data from sources that are completely time zone agnostic (e.g., all time is relative to UTC clock, without any time zone attributions on data points).
 *
 */
export class FallbackTimeZone extends SpeakeasyBase {
    /**
     *
     * @remarks
     *     Fallback time zone of the user, in the form of a valid IANA tzdatabase identifier (e.g., `Europe/London` or `America/Los_Angeles`).
     *     Used when pulling data from sources that are completely time zone agnostic (e.g., all time is relative to UTC clock, without any time zone attributions on data points).
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * Slug for designated source
     */
    @SpeakeasyMetadata()
    @Expose({ name: "source_slug" })
    sourceSlug: string;

    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    updatedAt: Date;
}

export class ClientFacingUser extends SpeakeasyBase {
    /**
     * A unique ID representing the end user. Typically this will be a user ID from your application. Personally identifiable information, such as an email address or phone number, should not be used in the client_user_id.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "client_user_id" })
    clientUserId: string;

    /**
     * A list of the users connected sources.
     */
    @SpeakeasyMetadata({ elemType: ConnectedSourceClientFacing })
    @Expose({ name: "connected_sources" })
    @Type(() => ConnectedSourceClientFacing)
    connectedSources: ConnectedSourceClientFacing[];

    /**
     * When your item is created
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_on" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    createdOn: Date;

    /**
     *
     * @remarks
     *     Fallback time zone of the user, in the form of a valid IANA tzdatabase identifier (e.g., `Europe/London` or `America/Los_Angeles`).
     *     Used when pulling data from sources that are completely time zone agnostic (e.g., all time is relative to UTC clock, without any time zone attributions on data points).
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fallback_time_zone" })
    @Type(() => FallbackTimeZone)
    fallbackTimeZone?: FallbackTimeZone;

    /**
     * Your team id.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "team_id" })
    teamId: string;

    /**
     * User id returned by vital create user request. This id should be stored in your database against the user and used for all interactions with the vital api.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "user_id" })
    userId: string;
}
