/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RFCDate } from "../../../sdk/types";
import { Expose, Transform, Type } from "class-transformer";

/**
 * Heart rate daily summary.
 */
export class HeartRate extends SpeakeasyBase {
    /**
     * Average heart rate::bpm
     */
    @SpeakeasyMetadata()
    @Expose({ name: "avg_bpm" })
    avgBpm?: number;

    /**
     * Maximum heart rate::bpm
     */
    @SpeakeasyMetadata()
    @Expose({ name: "max_bpm" })
    maxBpm?: number;

    /**
     * Minimum heart rate::bpm
     */
    @SpeakeasyMetadata()
    @Expose({ name: "min_bpm" })
    minBpm?: number;

    /**
     * Resting heart rate::bpm
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resting_bpm" })
    restingBpm?: number;
}

/**
 * Source the data has come from.
 */
export class ClientFacingActivitySource extends SpeakeasyBase {
    /**
     * The identifier of the app which recorded this summary. This is only applicable to multi-source providers like Apple Health and Android Health Connect.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "app_id" })
    appId?: string;

    /**
     * Deprecated.
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "logo" })
    logo: string;

    /**
     * Deprecated.
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * Provider slug. e.g., `oura`, `fitbit`, `garmin`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "provider" })
    provider: string;

    /**
     * Deprecated.
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "slug" })
    slug: string;

    /**
     * The type of the data source (app or device) by which the summary or the timeseries data were recorded. This defaults to `unknown` when Vital cannot extract or infer that information
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: string;
}

export class ClientFacingActivity extends SpeakeasyBase {
    /**
     * Date of the summary in the YYYY-mm-dd format.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "calendar_date" })
    @Type(() => String)
    @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
    calendarDate: RFCDate;

    /**
     * Energy consumption caused by the physical activity of the day in kilocalories::kilocalories
     */
    @SpeakeasyMetadata()
    @Expose({ name: "calories_active" })
    caloriesActive?: number;

    /**
     * Total energy consumption during the day including Basal Metabolic Rate in kilocalories::kilocalories
     */
    @SpeakeasyMetadata()
    @Expose({ name: "calories_total" })
    caloriesTotal?: number;

    /**
     * Deprecated. Daily physical activity as equal meters i.e. amount of walking needed to get the same amount of activity::meters
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "daily_movement" })
    dailyMovement?: number;

    /**
     * Date of the specified record, formatted as ISO8601 datetime string in UTC 00:00. Deprecated in favour of calendar_date.
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "date" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    date: Date;

    /**
     * Distance traveled during activities throughout the day::meters
     */
    @SpeakeasyMetadata()
    @Expose({ name: "distance" })
    distance?: number;

    /**
     * Number of floors climbed by the user::count
     */
    @SpeakeasyMetadata()
    @Expose({ name: "floors_climbed" })
    floorsClimbed?: number;

    /**
     * Heart rate daily summary.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "heart_rate" })
    @Type(() => HeartRate)
    heartRate?: HeartRate;

    /**
     * Number of minutes during the day with high intensity activity (e.g. running)::minutes
     */
    @SpeakeasyMetadata()
    @Expose({ name: "high" })
    high?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * Number of minutes during the day with low intensity activity (e.g. household work)::minutes
     */
    @SpeakeasyMetadata()
    @Expose({ name: "low" })
    low?: number;

    /**
     * Number of minutes during the day with medium intensity activity (e.g. walking)::minutes
     */
    @SpeakeasyMetadata()
    @Expose({ name: "medium" })
    medium?: number;

    /**
     * Source the data has come from.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "source" })
    @Type(() => ClientFacingActivitySource)
    source: ClientFacingActivitySource;

    /**
     * Total number of steps registered during the day::steps
     */
    @SpeakeasyMetadata()
    @Expose({ name: "steps" })
    steps?: number;

    /**
     * [DEPRECATED] The time zone full identifier for the data. Example: 'Europe/London'.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "time_zone" })
    timeZone?: string;

    /**
     * Timezone offset from UTC as seconds. For example, EEST (Eastern European Summer Time, +3h) is 10800. PST (Pacific Standard Time, -8h) is -28800::seconds
     */
    @SpeakeasyMetadata()
    @Expose({ name: "timezone_offset" })
    timezoneOffset?: number;

    /**
     * User id returned by vital create user request. This id should be stored in your database against the user and used for all interactions with the vital api.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "user_id" })
    userId: string;
}
