/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ShippingAddress } from "./shippingaddress";
import { Expose, Type } from "class-transformer";

export class CreateRegistrableTestkitOrderRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "lab_test_id" })
    labTestId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "shipping_details" })
    @Type(() => ShippingAddress)
    shippingDetails: ShippingAddress;

    @SpeakeasyMetadata()
    @Expose({ name: "user_id" })
    userId: string;
}
