/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Consent } from "./consent";
import { HealthInsuranceCreateRequest } from "./healthinsurancecreaterequest";
import { PatientAddressCompatible } from "./patientaddresscompatible";
import { PatientDetails } from "./patientdetails";
import { PhysicianCreateRequest } from "./physiciancreaterequest";
import { Expose, Type } from "class-transformer";

/**
 * Schema for the create Order endpoint.
 */
export class CreateOrderRequestCompatible extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: Consent })
    @Expose({ name: "consents" })
    @Type(() => Consent)
    consents?: Consent[];

    @SpeakeasyMetadata()
    @Expose({ name: "health_insurance" })
    @Type(() => HealthInsuranceCreateRequest)
    healthInsurance?: HealthInsuranceCreateRequest;

    @SpeakeasyMetadata()
    @Expose({ name: "lab_test_id" })
    labTestId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "patient_address" })
    @Type(() => PatientAddressCompatible)
    patientAddress: PatientAddressCompatible;

    @SpeakeasyMetadata()
    @Expose({ name: "patient_details" })
    @Type(() => PatientDetails)
    patientDetails: PatientDetails;

    @SpeakeasyMetadata()
    @Expose({ name: "physician" })
    @Type(() => PhysicianCreateRequest)
    physician?: PhysicianCreateRequest;

    /**
     * Defines whether order is priority or not. Only available for Labcorp. For Labcorp, this corresponds to a STAT order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "priority" })
    priority?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "user_id" })
    userId: string;
}
