/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RFCDate } from "../../types";
import { TimeSlot } from "./timeslot";
import { Expose, Transform, Type } from "class-transformer";

export class DaySlots extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "date" })
    @Type(() => String)
    @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
    date: RFCDate;

    @SpeakeasyMetadata({ elemType: TimeSlot })
    @Expose({ name: "slots" })
    @Type(() => TimeSlot)
    slots: TimeSlot[];
}
