/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * An enumeration.
 */
export enum DemoProviders {
    AppleHealthKit = "apple_health_kit",
    Fitbit = "fitbit",
    FreestyleLibre = "freestyle_libre",
    Oura = "oura",
}
