/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ClientFacingOrder } from "./clientfacingorder";
import { Expose, Type } from "class-transformer";

export class GetOrdersResponse extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: ClientFacingOrder })
    @Expose({ name: "orders" })
    @Type(() => ClientFacingOrder)
    orders: ClientFacingOrder[];

    @SpeakeasyMetadata()
    @Expose({ name: "page" })
    page: number;

    @SpeakeasyMetadata()
    @Expose({ name: "size" })
    size: number;

    @SpeakeasyMetadata()
    @Expose({ name: "total" })
    total: number;
}
