/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * An enumeration.
 */
export enum IngestibleTimeseriesResource {
    BloodPressure = "blood_pressure",
    BloodOxygen = "blood_oxygen",
    Glucose = "glucose",
    Heartrate = "heartrate",
    HeartrateVariability = "heartrate_variability",
    Water = "water",
    Caffeine = "caffeine",
    MindfulnessMinutes = "mindfulness_minutes",
}
