/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The type of sample used to perform a lab test.
 */
export enum LabTestSampleType {
    DriedBloodSpot = "dried_blood_spot",
    Serum = "serum",
    Saliva = "saliva",
    Urine = "urine",
}
