/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class LibreConfigPracticeId extends SpeakeasyBase {}

export class LibreConfig extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "practice_id" })
    @Type(() => LibreConfigPracticeId)
    practiceId: LibreConfigPracticeId;
}
