/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class OauthInfo extends SpeakeasyBase {}

export class LinkTokenBase extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "is_used" })
    isUsed?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "oauth_info" })
    @Type(() => OauthInfo)
    oauthInfo?: OauthInfo;

    @SpeakeasyMetadata()
    @Expose({ name: "token" })
    token: string;
}
