/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class LngLat extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "lat" })
    lat: number;

    @SpeakeasyMetadata()
    @Expose({ name: "lng" })
    lng: number;
}
