/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * An enumeration.
 */
export enum OpenLoopResourceIdType {
    Appointment = "Appointment",
    FormAnswerGroup = "FormAnswerGroup",
    Entry = "Entry",
    Note = "Note",
}
