/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { OpenLoopResourceIdType } from "./openloopresourceidtype";
import { OpenLoopWebhookType } from "./openloopwebhooktype";
import { Expose } from "class-transformer";

export class OpenLoopEvent extends SpeakeasyBase {
    /**
     * An enumeration.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "event_type" })
    eventType: OpenLoopWebhookType;

    @SpeakeasyMetadata()
    @Expose({ name: "resource_id" })
    resourceId: string;

    /**
     * An enumeration.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "resource_id_type" })
    resourceIdType: OpenLoopResourceIdType;
}
