/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * An enumeration.
 */
export enum OrderTopLevelStatus {
    Received = "received",
    CollectingSample = "collecting_sample",
    SampleWithLab = "sample_with_lab",
    Completed = "completed",
    Cancelled = "cancelled",
    Failed = "failed",
}
