/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AuthType } from "./authtype";
import { Providers } from "./providers";
import { Expose } from "class-transformer";

export class PasswordAuthLink extends SpeakeasyBase {
    /**
     * An enumeration.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "auth_type" })
    authType: AuthType;

    @SpeakeasyMetadata()
    @Expose({ name: "password" })
    password: string;

    /**
     * An enumeration.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "provider" })
    provider: Providers;

    @SpeakeasyMetadata()
    @Expose({ name: "username" })
    username: string;
}
