/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Gender } from "./gender";
import { Expose, Transform } from "class-transformer";

export class PatientDetails extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "dob" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    dob: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email: string;

    @SpeakeasyMetadata()
    @Expose({ name: "first_name" })
    firstName: string;

    /**
     * An enumeration.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gender" })
    gender: Gender;

    @SpeakeasyMetadata()
    @Expose({ name: "last_name" })
    lastName: string;

    @SpeakeasyMetadata()
    @Expose({ name: "phone_number" })
    phoneNumber: string;
}
