/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * An enumeration.
 */
export enum Region {
    Us = "us",
    Eu = "eu",
    Sg = "sg",
    De = "de",
    Au = "au",
    Br = "br",
    Nl = "nl",
    Fr = "fr",
}
