/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * An enumeration.
 */
export enum ResponsibleRelationship {
    Self = "Self",
    Spouse = "Spouse",
    OtherRelationship = "Other Relationship",
}
