/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * An enumeration.
 */
export enum SourceSourceAuthType {
    Oauth = "oauth",
    TeamOauth = "team_oauth",
    SDK = "sdk",
    Password = "password",
    Email = "email",
    App = "app",
    Unknown = "",
}

/**
 * An enumeration.
 */
export enum SourceType {
    App = "app",
    Ble = "ble",
    Device = "device",
    Lab = "lab",
    Provider = "provider",
}

export class Source extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "auth_type" })
    authType?: SourceSourceAuthType;

    @SpeakeasyMetadata()
    @Expose({ name: "backfill_num_days" })
    backfillNumDays?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description: string;

    @SpeakeasyMetadata()
    @Expose({ name: "group" })
    group?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    @SpeakeasyMetadata()
    @Expose({ name: "is_active" })
    isActive?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "logo" })
    logo: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "oauth_url" })
    oauthUrl?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "slug" })
    slug: string;

    @SpeakeasyMetadata()
    @Expose({ name: "source_type" })
    sourceType?: SourceType;
}
