/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * An enumeration.
 */
export enum SourceLinkSourceAuthType {
    Oauth = "oauth",
    TeamOauth = "team_oauth",
    SDK = "sdk",
    Password = "password",
    Email = "email",
    App = "app",
    Unknown = "",
}

export class FormComponents extends SpeakeasyBase {}

export class SourceLink extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "auth_type" })
    authType?: SourceLinkSourceAuthType;

    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description: string;

    @SpeakeasyMetadata()
    @Expose({ name: "form_components" })
    @Type(() => FormComponents)
    formComponents?: FormComponents;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    @SpeakeasyMetadata()
    @Expose({ name: "logo" })
    logo: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "oauth_url" })
    oauthUrl?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "slug" })
    slug: string;
}
