/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * An enumeration.
 */
export enum SourceAuthType {
    Oauth = "oauth",
    TeamOauth = "team_oauth",
    SDK = "sdk",
    Password = "password",
    Email = "email",
    App = "app",
    Unknown = "",
}
