/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { LibreConfig } from "./libreconfig";
import { Expose, Type } from "class-transformer";

export class TeamConfig extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "libreview" })
    @Type(() => LibreConfig)
    libreview: LibreConfig;

    @SpeakeasyMetadata()
    @Expose({ name: "texts_enabled" })
    textsEnabled?: boolean;
}
