/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class UserRefreshSuccessResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "failed_sources" })
    failedSources: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "refreshed_sources" })
    refreshedSources: string[];

    /**
     * Whether operation was successful or not
     */
    @SpeakeasyMetadata()
    @Expose({ name: "success" })
    success: boolean;

    /**
     * A unique ID representing the end user. Typically this will be a user ID from your application. Personally identifiable information, such as an email address or phone number, should not be used in the client_user_id.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "user_id" })
    userId: string;
}
