/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class UserSignInTokenResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "sign_in_token" })
    signInToken: any;

    @SpeakeasyMetadata()
    @Expose({ name: "user_id" })
    userId: string;
}
