/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class UserCreateBody extends SpeakeasyBase {
    /**
     * A unique ID representing the end user. Typically this will be a user ID from your application. Personally identifiable information, such as an email address or phone number, should not be used in the client_user_id.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "client_user_id" })
    clientUserId: string;

    /**
     *
     * @remarks
     *     Fallback time zone of the user, in the form of a valid IANA tzdatabase identifier (e.g., `Europe/London` or `America/Los_Angeles`).
     *     Used when pulling data from sources that are completely time zone agnostic (e.g., all time is relative to UTC clock, without any time zone attributions on data points).
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fallback_time_zone" })
    fallbackTimeZone?: string;
}
