/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

/**
 * Successful Response
 */
export class CheckLinkTokenStateV2LinkStateGetResponseCheckLinkTokenStateV2LinkStateGet extends SpeakeasyBase {}

export class CheckLinkTokenStateV2LinkStateGetResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Successful Response
     */
    @SpeakeasyMetadata()
    responseCheckLinkTokenStateV2LinkStateGet?: CheckLinkTokenStateV2LinkStateGetResponseCheckLinkTokenStateV2LinkStateGet;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;
}
