/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

/**
 * An enumeration.
 */
export enum ConnectEmailAuthProviderV2LinkProviderEmailProviderPostProviderEmailProviders {
    FreestyleLibre = "freestyle_libre",
}

export class ConnectEmailAuthProviderV2LinkProviderEmailProviderPostRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    emailProviderAuthLink: shared.EmailProviderAuthLink;

    /**
     * An enumeration.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=provider" })
    provider: ConnectEmailAuthProviderV2LinkProviderEmailProviderPostProviderEmailProviders;
}

export class ConnectEmailAuthProviderV2LinkProviderEmailProviderPostResponse extends SpeakeasyBase {
    /**
     * Successful Response
     */
    @SpeakeasyMetadata()
    connectionStatus?: shared.ConnectionStatus;

    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
