/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class GetTeamUserCountV2TeamTeamIdUsersCountGetRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=team_id" })
    teamId: string;
}

/**
 * Successful Response
 */
export class GetTeamUserCountV2TeamTeamIdUsersCountGetResponseGetTeamUserCountV2TeamTeamIdUsersCountGet extends SpeakeasyBase {}

export class GetTeamUserCountV2TeamTeamIdUsersCountGetResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Successful Response
     */
    @SpeakeasyMetadata()
    responseGetTeamUserCountV2TeamTeamIdUsersCountGet?: GetTeamUserCountV2TeamTeamIdUsersCountGetResponseGetTeamUserCountV2TeamTeamIdUsersCountGet;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
