/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class UpdateApiKeyLabelV2TeamTeamIdApikeyApiKeyIdPatchRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    updateApiKeyBody: shared.UpdateApiKeyBody;

    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=api_key_id" })
    apiKeyId: string;

    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=team_id" })
    teamId: string;
}

export class UpdateApiKeyLabelV2TeamTeamIdApikeyApiKeyIdPatchResponse extends SpeakeasyBase {
    /**
     * Successful Response
     */
    @SpeakeasyMetadata()
    apiKeyInDB?: shared.ApiKeyInDB;

    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
